#ifndef C_PROJ_MAIN_H
#define C_PROJ_MAIN_H

#include "MemoryObject.h"
#include "datastructs/ByteCode.h"
#include "Value.h"

#include "codes/Halt.h"
#include "add.h"
#include "call.h"
#include "cmpe.h"
#include "cmpgt.h"
#include "cmplt.h"
#include "div.h"
#include "Halt.h"
#include "jmp.h"
#include "jmpc.h"
#include "mul.h"
#include "peekc.h"
#include "peekf.h"
#include "peeki.h"
#include "peeks.h"
#include "pokec.h"
#include "pokef.h"
#include "pokei.h"
#include "pokes.h"
#include "popa.h"
#include "popm.h"
#include "popv.h"
#include "printc.h"
#include "Printf.h"
#include "printi.h"
#include "prints.h"
#include "Pushc.h"
#include "Pushi.h"
#include "Pushs.h"
#include "pushf.h"
#include "pushvc.h"
#include "pushvf.h"
#include "pushvi.h"
#include "pushvs.h"
#include "ret.h"
#include "sub.h"
#include "swp.h"

#include "Stack.h"
#include <iostream>
#include <sys/stat.h>
#include <stdio.h>
#include <fstream>
#include <vector>

#endif //C_PROJ_MAIN_H
